[databases]
; sintaxis: dbname = host=ADDR port=PORT dbname=DBNAME
nova = host=127.0.0.1 port=5432 dbname=nova

[pgbouncer]
; Red
listen_addr = 0.0.0.0
listen_port = 6432

; Auth
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

; Pool settings
pool_mode = session
max_client_conn = 100
default_pool_size = 20
reserve_pool_size = 5
reserve_pool_timeout = 3

; Timeouts (segundos)
query_timeout = 60
query_wait_timeout = 30
server_login_retry = 3

; Logging
syslog = 0
log_connections = 0
log_disconnections = 0
log_pooler_errors = 1

; Misc
server_reset_query = DISCARD ALL
server_check_delay = 30
server_lifetime = 3600
server_idle_timeout = 600
